Update patch set 7
Patch Set 7:

> The failing build mentions -Werror -Wsign-compare
> which is supposed to be a part of -Wall

Turns out I haven't read this properly - it's inside -Wall only in C++ mode.  In C it's -Wextra, so the Goobuntu GCC behaves according to its man page, albeit differently from other systems.  Maybe we want -Wextra too (and -pedantic, while there)?

$ cat a.c
int main() { return main() > sizeof(int); }
$ CFLAGS="-Wall -Werror" make a                                                                                                                                                                                                                                                                                               
cc -Wall -Werror    a.c   -o a
$ rm a                                                                                                                                                                                                                                                                                                                        
$ CFLAGS="-Wall -Werror -Wsign-compare" make a                                                                                                                                                                                                                                                                                
cc -Wall -Werror -Wsign-compare    a.c   -o a
a.c: In function ‘main’:
a.c:1:28: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
 int main() { return main() > sizeof(int); }
                            ^
cc1: all warnings being treated as errors
make: *** [a] Error 1

Patch-set: 7
Label: Verified=0