Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > What I tested is to build minijail on host for Android. In that case, it still uses glibc.
> 
> true, for the build-time stuff, their toolchain is ancient
> 
> although glibc-2.15 also included si_syscall, so that shouldn't be an issue.  did you implement my full suggestion and not just delete the defines/includes ?

Do you mean to remove local_sigsys? I tried that, and got errors like
external/minijail/signal_handler.c:23:53: error: no member named '_sigsys' in 'union siginfo::(anonymous at prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/sysroot/usr/include/x86_64-linux-gnu/bits/siginfo.h:58:5)'
       syscall_name = lookup_syscall_name(info->_sifields._sigsys._syscall);


It does not have _sigsis in _sifields for glibc 2.15

Patch-set: 5
Reviewer: Gerrit User 1087590 <1087590@85c56323-6fa9-3386-8a01-6480fb634889>