minijail0: implement --clear-env and --set-env
The default behavior of minijail0 is to transmit its own environment
to the program it launches.
These two options enable modification of this standard behavior, by
setting up a specific environment for the target program.

* --clear-env prevents minijail0 to pass its own environment to the
program. Note that if this option is used without any --set-env option,
the program starts with a completely empty environment.

* --set-env allows setting any number of environment variables to be
added to the environment set up for the program. Note that the special
environment variable LD_PRELOAD can also be set this way, without
impacting minijail0's own invocation.

Test: make tests

Test: `minijail0 --clear-env --set-env LD_PRELOAD="a b" --set-env FOO=bar /usr/bin/env`
"""
ERROR: ld.so: object 'a' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'b' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
LD_PRELOAD=a b
FOO=bar
"""

Change-Id: I2e106003824ff6707b80b6653141657e4ec40f47